INSERT INTO wp_politeia_political_parties (official_name, short_name, founded_on, dissolved_on, ideology)
VALUES
  ('Renovación Nacional', 'RN', NULL, NULL, 'Centre-right to right-wing'),
  ('Unión Demócrata Independiente', 'UDI', NULL, NULL, 'Right-wing'),
  ('Evolución Política', 'Evópoli', NULL, NULL, 'Centre-right'),
  ('Partido Socialista de Chile', 'PS', NULL, NULL, 'Centre-left'),
  ('Partido por la Democracia', 'PPD', NULL, NULL, 'Centre-left'),
  ('Partido Radical de Chile', 'PR', NULL, NULL, 'Centre-left'),
  ('Partido Liberal de Chile', 'PL', NULL, NULL, 'Liberalism'),
  ('Frente Amplio', 'FA', NULL, NULL, 'Left-wing'),
  ('Partido Demócrata Cristiano', 'PDC', NULL, NULL, 'Christian democracy'),
  ('Partido Comunista de Chile', 'PC', NULL, NULL, 'Left-wing to far-left'),
  ('Demócratas', 'Demócratas', NULL, NULL, 'Centre to centre-right'),
  ('Partido Social Cristiano', 'PSC', NULL, NULL, 'Right-wing'),
  ('Partido Republicano de Chile', 'PLR', NULL, NULL, 'Right-wing'),
  ('Federación Regionalista Verde Social', 'FRVS', NULL, NULL, 'Centre-left to left-wing'),
  ('Partido Nacional Libertario', 'PNL', NULL, NULL, 'Right-wing'),
  ('Acción Humanista', 'AH', NULL, NULL, 'Left-wing'),
  ('Amarillos por Chile', 'AxCh', NULL, NULL, 'Centre'),
  ('Partido de la Gente', 'PDG', NULL, NULL, 'Centre-right to right-wing'),
  ('Partido Humanista', 'PH', NULL, NULL, 'Left-wing'),
  ('Partido Alianza Verde Popular', 'PAVP', NULL, NULL, 'Centre-left'),
  ('Partido Popular', 'Popular', NULL, NULL, 'Left-wing'),
  ('Partido Igualdad', 'IGUAL', NULL, NULL, 'Left-wing to far-left'),
  ('Partido de Trabajadores Revolucionarios', 'PTR', NULL, NULL, 'Far-left');
